markdown: kramdown

# Disable Liquid ONLY for posts folder
defaults:
  - scope:
      path: "posts"
      type: "posts"
    values:
      render_with_liquid: false

liquid:
  error_mode: warn
  strict_filters: false
